name: Build and Upload Debian Package

on:
  push:
    branches:
      - main
  release:
    types: [released]

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          outputs: build
      - uses: paulhatch/semantic-version@v4
        id: semantic
        with:
          tag_prefix: ""
          format: ${{ github.event_name == 'release' && '${major}.${minor}.${patch}' || '${major}.${minor}.${patch}-prerelease${increment}' }}
          bump_each_commit: true
      - uses: jiro4989/build-deb-action@v2
        id: build
        with:
          package: muxable-libnvmpi
          package_root: ./build
          maintainer: Kevin Wang <kevin@muxable.com>
          version: ${{ steps.semantic.outputs.version }}
          arch: 'arm64'
      - uses: actions/upload-artifact@v3
        with:
          name: libnvmpi-arm64.deb
          path: ${{ steps.build.outputs.file_name }}

  unstable-deploy:
    needs: deb
    runs-on: ubuntu-latest
    environment:
      name: muxer-unstable
      url: https://console.cloud.google.com/artifacts/apt/muxable/us-central1/muxer-unstable?project=muxable
    concurrency: 
      group: muxer-unstable-${{ github.ref }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: libnvmpi-arm64.deb
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.MUXABLE_ARTIFACT_REGISTRY_SERVICE_ACCOUNT_JSON }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload packages to Google Cloud unstable
        run: ls *.deb | xargs -I{} gcloud artifacts apt upload muxer-unstable --location=us-central1 --source={}

  stable-deploy:
    if: github.event_name == 'release'
    needs: deb
    runs-on: ubuntu-latest
    environment:
      name: muxer-stable
      url: https://console.cloud.google.com/artifacts/apt/muxable/us-central1/muxer-stable?project=muxable
    concurrency: 
      group: muxer-stable-${{ github.ref }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: libnvmpi-arm64.deb
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.MUXABLE_ARTIFACT_REGISTRY_SERVICE_ACCOUNT_JSON }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload packages to Google Cloud stable
        run: ls *.deb | xargs -I{} gcloud artifacts apt upload muxer-stable --location=us-central1 --source={}